### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by carlosarias1992** [carlosarias1992/Fakebook#2]
## New account creation, login, and guest/demo login

- [x] MVP is completely styled and seeded
- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + R)
- [x] MVP handles errors with informative messages for user
- [x] Users can sign up, sign in, and log out.
- [x] Users can explore the site with a demo login.
- [x] Users can't see the feed page without logging in.

**Comment by jliversi** [comment]
Amazing work so far, there are a few things to fix. 
- [ ] If you start typing in a login at the top of the page and then backspace it away, the error icon renders on top of the log in button. 
- [ ] Your errors aren't being handled exactly like facebook's are (see image below). Make sure to pass up the errors from the backend and render them above so users can see if the cause of the failed sign up is a short password or a already-taken username (etc). 
- [ ] Also in the image below, you can see there's a second email input field for confirming your email (which only appears after you finish typing in the first one). Implement this as well. 

![Screen Shot 2019-03-27 at 4 49 03 PM](https://user-images.githubusercontent.com/43765782/55111230-4db9d000-50b0-11e9-94e5-aa27b2aa7786.png)

Really solid work overall though.
