### ISSUE TITLE
Friending

### ISSUE THREAD

**Issue by carlosarias1992** [carlosarias1992/Fakebook#5]
## Friending

 - [ ] MVP is completely styled and seeded
 - [ ] MVP is bug free with smooth navigation
 - [x]  MVP is bug free on a hard refresh (⌘ + R)
 - [x]  MVP handles errors with informative messages for user
 - [x]  A user can send a request to another user to become friends.
 - [ ]  A user can accept or deny a friend request.

**Comment by jliversi** [comment]
- [ ] Currently, when you "delete request", it removes it from that request box, but does not actually remove it entirely, and it is there again upon refresh. 
- [ ] Your notifications should only be for NEW requests. Currently, if you have 1 request sitting in your inbox, with the notifications cleared, and then you get a new request, the indicator at the top shows a "2". This should be a "1" for one NEW request (even though you have a total of 2 requests overall). 
- [ ] Once a friend request is accepted, and two users are friends, it seems like ONLY the user who originally SENT the request is able to "unfriend". The other can click "unfriend", and it seems to remove them from their friend's list, but upon refresh the friendship is still there. Refactor to make this relationship symmetrical.
